### PR TITLE
get_session / set_session modifications (reviving deleted keys)

### PR DESCRIPTION
**Pull request by vspy**
Actually, deleting keys form session wasn't working before. Session object in get_session and set_session are completely different objects, so passing hash through “old” never worked (And I tried that with multiple rack versions). That is why it always were reviving deleted keys.

### CODE REVIEW

**Comment by vspy** [comment]
i think something is still very wrong. I'll better provide a properly tested fix later

**Comment by vspy** [comment]
It was fine in the end. You can actually merge this, works perfectly for me.

**Comment by jfairbairn** [comment]
I wrote a test that reproduced the bug, and proves that your patch does fix that bug. It's here: 

https://github.com/jfairbairn/rack-session-redis/commit/8193539566df216bc5b4682f0f4ef037f17a199b

**Comment by jfairbairn** [comment]
Oh, I decided to make a pull request for that, #3. Then I figured out that it also included the commits from #1, and #2. Oops. n00b alert. Oh well, GitHub magic probably means that if #3 gets applied, all the outstanding pull requests will magically be closed. :)

**Pull request merged**
